### ISSUE TITLE
Vis Library v1.0 Wish List

### ISSUE THREAD

**Issue by chnn** [influxdata/giraffe#91]
So far we've implemented a very scarce set of features that meet the minimum requirements of the [InfluxDB UI](https://github.com/influxdata/influxdb). We should think about the features we want for a worthy v1.0 release of giraffe. 

I would propose:

- [ ] A better story for processing tables in a `WebWorker`
- [ ] A faceting/layout API
- [ ] Support for bar graphs with a discrete x/y domain
- [ ] Support for single stat and gauge visualizations
- [ ] Support for area/stacked area layers
- [x] Rich tick formatting support, including timezone support for date ticks
- [x] A `fromRows` adapter for creating a `Table` from a list of javascript objects (the canonical JS input to a visualization library)
- [ ] An API for custom layer types that make use of shared scales and interaction events
- [ ] A doc site with guides and sandbox examples

**Comment by TCL735** [comment]
While some of these are still valid and pending, we will close this issue for being too broad. Individual issues should be created instead.
